function [m,V,alpha,chi,cp] = bgcBulkParam(components)
% Compute bulk parameters from components structures of the
% kind generated by bgcParam.m
%
% Revision History
% 2012-12-27    mvj    Created.  See derivation in today's notes.

m = sum([components(:).m]);
V = sum([components(:).V]);
alpha = sum([components(:).V].*[components(:).alpha])/V;
chi = sum([components(:).V].*[components(:).chi])/V;
cp = NaN; % weight by mass? 
