% Clio vehicle simulation.
%
%
% Function library:
% =================
%
% Vehicle Modeling:
%
%  bgcAddComponent         - Add a component to a vehicle model.
%  bcgAddSldComponent      - Add a component defined in formatted output generated by 
%                            Solidworks.
%  bgcInitComponent        - Initialize a component to add to a vehicle model.
%  bgcParam                - Defines a vehicle model.
%  bgcNeutral              - Compute the volume of a material necessary to make a 
%                            vehicle neutral at a depth.
%  bgcMatl                 - An archive of relevant material properties.
%
% Net Material Properties:
%
%  bgcVolume               - Compute volume at depth for a vehicle model.
%  bgcBulkParam            - Compute bulk (net) parameters for a vehicle model.
%
% Simulation Events:  
%
%   These functions return true when certain conditions are met to interrupt 
%   and alter simulation.  Used with ode45 to allow for hybrid discrete/continuous 
%   simulations.
%
%   bgcEventBounds         - Indicates contact with a free surface and sea floor. 
%   bgcEventControl        - Engages closed-loop control of depth.
%   bgcEventDropWeight     - Drops a simulated drop-weight.
%   bgcEventFilter         - Simulates taking a SUPR sample (filtering).
%   bgcEventThrustDown     - Thrust down until reaching a specified depth.
%   bgcEventPrintStatus    - Print simulation status to console.
%   bgcEventNone           - Never true.
%   bgcEvents              - Aggregates event functions.
%
%
% Simulation 
%
%   bgc.m                  - Main function.  Runs a simulation.
%   bgcFeedback.m          - implements closed loop control of depth.
%   bgcIntegrator.m        - Implements the I term in a PID loop.
%   bgcF.m                 - Vehicle dynamics from vehicle model.  Wraps ode45.
%   bgcPlot.m              - Plot simulation output.oo
%
% Environment
%
%   bgcInSitu.m            - Interpolate for in situ seawater properties given 
%                            a profile and depth. 
%   bgcProfile.m           - Background seawater profile (Levitus 1982).
%
% Miscellaneous
%
%   bgcBruntVaisala        - Undamped frequency of oscillation for a profiler 
%                            at its neutral depth.
%   bgcConst               - physical constants.
%   bgcConversions         - Conversions between units
%   
% Helper functions and libraries
%
% seawater           - MATLAB routines to compute seawater properties (see sw_info.m for credit)
% util               - Misc. utility functions to make this project self-contained
% vehicle            - Archive of vehicle models from the Clio design project, 2012-2017

% Revision History
% 2014-05-28    mvj    Added this documentation.
% 2018-01-29    mvj    Added documentation of individual functions.
% 2018-02-13    mvj    completed doco.

